### ISSUE TITLE
the quicksort example fails

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/ppft#4]
Fails for 2.x and 3.x, with (at least the `dill` master).

```
>$ python quicksort.py 
Usage: python quicksort.py [ncpus]
    [ncpus] - the number of workers to run in parallel, 
    if omitted it will be set to the number of processors in the system

Starting pp with 8 workers
An error has occured during the function import
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python2.7/site-packages/ppft-1.6.4.6.dev0-py2.7.egg/ppworker.py", line 82, in run
    exec __fobj
  File "<string>", line 1, in <module>
ImportError: cannot import name quicksort
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python2.7/site-packages/ppft-1.6.4.6.dev0-py2.7.egg/ppworker.py", line 91, in run
    __f = locals()[__fname]
KeyError: 'quicksort'
Traceback (most recent call last):
  File "quicksort.py", line 66, in <module>
    output.extend(x())
TypeError: 'NoneType' object is not iterable
```

This ultimately comes from `dill.source.importable` failing to get the source/import correctly.

**Comment by mmckerns** [comment]
this has been fixed
