### ISSUE TITLE
JVM already allocates SIGUSR1

### ISSUE THREAD

**Issue by seansummers** [uqfoundation/ppft#5]
When running `ppserver.py` on jython 1.7.0, the following occurs:
```
root@2c8f12ad27e3:/# /usr/local/jython-2.7.0/bin/ppserver.py
Traceback (most recent call last):
  File "/usr/local/jython-2.7.0/bin/ppserver.py", line 397, in <module>
    signal.signal(signal.SIGUSR1, signal_handler)
  File "/usr/local/jython-2.7.0/Lib/signal.py", line 139, in signal
    prev = _register_signal(signal, JythonSignalHandler(action))
  File "/usr/local/jython-2.7.0/Lib/signal.py", line 155, in _register_signal
    raise ValueError(err.getMessage())
ValueError: Signal already used by VM or OS: SIGUSR1

```
This is because SIGUSR1 is used by the JVM (even with +UseAltSigs).

**Comment by mmckerns** [comment]
Ok, thanks.  works for me.
