### ISSUE TITLE
pp throws RuntimeError on pp.Server init in python3.2

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/ppft#9]
NOTE: the following behavior is for the `dill` fork of `pp` (or `ppft`, which is essentially an alias).
This behavior is seen on at least a MacOSX for python 3.2.6.

```
>>> import pp
>>> pp.Server()
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.2/site-packages/pp-1.6.4.4-py3.2.egg/pp.py", line 372, in __init__
    self.set_ncpus(ncpus)
  File "/Users/mmckerns/lib/python3.2/site-packages/pp-1.6.4.4-py3.2.egg/pp.py", line 542, in set_ncpus
    range(ncpus - len(self.__workers))])
  File "/Users/mmckerns/lib/python3.2/site-packages/pp-1.6.4.4-py3.2.egg/pp.py", line 541, in <listcomp>
    self.__pickle_proto) for x in\
  File "/Users/mmckerns/lib/python3.2/site-packages/pp-1.6.4.4-py3.2.egg/pp.py", line 161, in __init__
    self.start()
  File "/Users/mmckerns/lib/python3.2/site-packages/pp-1.6.4.4-py3.2.egg/pp.py", line 175, in start
    self.pid = int(self.t.receive())
  File "/Users/mmckerns/lib/python3.2/site-packages/pp-1.6.4.4-py3.2.egg/pptransport.py", line 179, in receive
    raise RuntimeError("Communication pipe read error")
RuntimeError: Communication pipe read error

>>>
```

**Comment by mmckerns** [comment]
Not an issue for later versions of python, and 3.2 is no longer supported. Closing.
